---
title: "ReadMe file for the tidy data script"
output: html_document
---

This tidy data follows the principles of the hadley Wickham's paper - Tidy Data - http://vita.had.co.nz/papers/tidy-data.pdf


1. Each variable you measure should be in one column
2. Each different observation of that variable should be in a different row
3. There should be one table for each "kind" of variable
4. If you have multiple tables, they should include a column in the table that allows them to be linked


Also, tidy data also follows these principle

1. Each variable forms a column.
2. Each observation forms a row.
3. Each type of observational unit forms a table



Description of the script run_analysis.R to create a tidy data.


Step 1 - Read the test(subject, y, and X) and train data (subject, y, and X). All from working directory which is local.

Step 2 - Read the features.txt and activity_labels.txt file to R

Step 3 - Used rbing to join the rows of test and train folders (subject, y, X)

Step 4 - Changing column names to identifiable names for easy recognition for column extraction

Step 5 - Created a data set by using cbind combining already combined rows (Step 3) into variable "ttotal"

Step 6 - Extract mean and std columns along with Subject and Activity from data set "ttotal" using grep function

Step 7 - Extracted data set saved in "ttotalextracted" 

Step 8 -  Replaced Activity numbers in Activity column by labels from activity_labels by converting elements into factors and replacing them with labels

Step 9 - Made the variable names more readable by excluding () using make.names()

Step 10 - Used group_by () to create groups by subjects and then by activity. 

Step 11 - Used summarise_each () to get the mean the variable for each activity for each subject

Step 12 - Used write.table to convert tidy data into .txt file called tidy_data.txt. One can read this .txt file by using data <- read.table(file_path, header = TRUE) as mentioned in one of the discussion thread created by CTA David Hood.



Here's script below - 

## Reading in txt files from the test folder in the local computer

subject_test <- read.table("./test/subject_test.txt")
y_test <- read.table("./test/y_test.txt")
X_test <- read.table("./test/X_test.txt")

## Reading in txt files from the train folder in the local computer

subject_train <- read.table("./train/subject_train.txt")
y_train <- read.table("./train/y_train.txt")
X_train <- read.table("./train/X_train.txt")

## Reading txt files for features and activity_labels

features <- read.table("./features.txt")
activity_labels <- read.table("./activity_labels.txt")


##Combining rows for test and train data for subject (id)

subject_total <- rbind(subject_train, subject_test)


##Combining rows for test and train data for y (activity number)

y_total <- rbind(y_train, y_test)


##Combining rows for test and train data for X (561 variables of measurement)

X_total <- rbind(X_train, X_test)

## Changing column names to make it more idenfiable for extraction purposes

colnames(subject_total)= "Subject"

colnames(y_total)= "Activity"

colnames(X_total) <- as.character(features$V2)


## Joining the columnns of the train and test total rows to create a data frame

ttotal <- cbind(subject_total, y_total, X_total)

## Extracting columns which have std and mean measurements.

ttotalextracted <- ttotal[,grep("mean|std|Activity|Subject", colnames(ttotal))]

## Replacing activity numbers with activity labels in the data set

ttotalextracted$Activity <- as.factor(ttotalextracted$Activity)
levels(ttotalextracted$Activity) <- c("Walking","Walking_Upstairs","Walking_Downstairs", "Sitting", "Standing", "Laying")

## Replacing variables names with more acceptable and readable variable name

names(ttotalextracted)<- make.names(names=names(ttotalextracted), unique=TRUE, allow_=TRUE)

##  Transfering contents of ttotalextracted to almost_tidy_data

almost_tidy_data <- ttotalextracted

## Using group_by function to group almost_tidy_data

almost_tidy_data_group_by <- group_by(almost_tidy_data, Subject, Activity)

## Using summarise_each function to find mean to each grpups in the data set

tidy_data <- summarise_each(almost_tidy_data_group_by, funs(mean))



## View tidy data set

View(tidy_data)

## Output file tidy_data.txt to working directory

write.table(tidy_data,file="./tidy_data.txt",row.names=FALSE)






